/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BloggingApp;



import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@Configuration
@EnableAutoConfiguration
@ComponentScan(basePackages = "com.cg.blogging")
@EnableJpaRepositories(basePackages="com.cg.blogging.repository")
@EntityScan(basePackages="com.cg.blogging.entities")
public class Library {
	public static void main(String[] args) {
		SpringApplication.run(Library.class,args);
	}
}

